# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Blag
tagline:          The stormtrooper that never misses
description:      "Moonshots from the stormtrooper that never misses"
url:              http://alfredgamulo.com
baseurl:          ""
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Alfred Gamulo
  twitter:        https://twitter.com/alfredgamulo
  github:         https://github.com/alfredgamulo

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
